package main

import (
	"crypto/hmac"
	"crypto/sha1"
	"encoding/base64"
	"fmt"
	"time"
)

// TURNCredentials holds time-limited TURN authentication credentials.
// These are generated by the master server and given to game clients
// so they can authenticate with coturn. The shared secret (TurnSecret)
// is NEVER sent to clients — only the HMAC-derived credential is.
type TURNCredentials struct {
	Username string   `json:"username"`
	Password string   `json:"password"`
	TTL      int      `json:"ttl"`
	URIs     []string `json:"uris"`
}

// TURNGenerator produces time-limited TURN credentials using the
// shared secret mechanism (RFC 5766, coturn "use-auth-secret" mode).
//
// How it works:
//  1. Username = "<expiry_unix_timestamp>:<random_id>"
//  2. Password = Base64(HMAC-SHA1(shared_secret, username))
//  3. coturn verifies by computing the same HMAC with its copy of the secret
//  4. coturn checks that the timestamp hasn't expired
//
// The shared secret never leaves the server.
type TURNGenerator struct {
	Secret string
	Host   string
	Port   int
	TTL    int // seconds
}

// NewTURNGenerator creates a credential generator with the given config.
func NewTURNGenerator(cfg *Config) *TURNGenerator {
	return &TURNGenerator{
		Secret: cfg.TurnSecret,
		Host:   cfg.TurnHost,
		Port:   cfg.TurnPort,
		TTL:    cfg.TurnCredentialTTL,
	}
}

// Generate creates a new set of time-limited TURN credentials.
// The userID should be a unique identifier for the requesting client
// (e.g., their game session ID or a random token).
func (t *TURNGenerator) Generate(userID string) TURNCredentials {
	expiry := time.Now().Unix() + int64(t.TTL)
	username := fmt.Sprintf("%d:%s", expiry, userID)

	mac := hmac.New(sha1.New, []byte(t.Secret))
	mac.Write([]byte(username))
	password := base64.StdEncoding.EncodeToString(mac.Sum(nil))

	return TURNCredentials{
		Username: username,
		Password: password,
		TTL:      t.TTL,
		URIs: []string{
			fmt.Sprintf("turn:%s:%d?transport=udp", t.Host, t.Port),
			fmt.Sprintf("stun:%s:%d", t.Host, t.Port),
		},
	}
}
